default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 15000

development:
  <<: *default
  database: test_heroku_api_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'postgres' %>

test:
  <<: *default
  database: test_heroku_test_<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'postgres' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
